"""Add view_count to hackathons table

Revision ID: add_view_count_to_hackathons
Revises: fix_notification_schema
Create Date: 2026-02-24 16:31:48.089000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_view_count_to_hackathons'
down_revision = 'fix_notification_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if view_count column already exists in hackathons table
    conn = op.get_bind()
    
    # Check for column existence
    col_result = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT FROM information_schema.columns "
            "WHERE table_name = 'hackathons' AND column_name = 'view_count')"
        )
    ).scalar()
    
    if not col_result:
        # Add view_count column to hackathons table with default 0
        op.add_column(
            'hackathons',
            sa.Column('view_count', sa.Integer(), nullable=False,
                      server_default='0')
        )
        
        # Create index for better query performance
        op.create_index(
            'ix_hackathons_view_count',
            'hackathons', ['view_count']
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop index
    op.drop_index('ix_hackathons_view_count', table_name='hackathons')
    
    # Drop column
    op.drop_column('hackathons', 'view_count')
    
    # ### end Alembic commands ###