"""Add team_id to projects table

Revision ID: add_team_id_to_projects
Revises: add_missing_tables
Create Date: 2026-02-20 18:27:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_team_id_to_projects'
down_revision = 'add_missing_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if team_id column already exists in projects table
    conn = op.get_bind()
    
    # Check for column existence
    col_result = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT FROM information_schema.columns "
            "WHERE table_name = 'projects' AND column_name = 'team_id')"
        )
    ).scalar()
    
    if not col_result:
        # Add team_id column to projects table
        op.add_column(
            'projects',
            sa.Column('team_id', sa.Integer(), nullable=True)
        )
        
        # Create foreign key constraint
        op.create_foreign_key(
            'fk_projects_team_id_teams',
            'projects', 'teams',
            ['team_id'], ['id']
        )
        
        # Create index for better query performance
        op.create_index(
            'ix_projects_team_id',
            'projects', ['team_id']
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint
    op.drop_constraint(
        'fk_projects_team_id_teams',
        'projects',
        type_='foreignkey'
    )
    
    # Drop index
    op.drop_index('ix_projects_team_id', table_name='projects')
    
    # Drop column
    op.drop_column('projects', 'team_id')
    
    # ### end Alembic commands ###