"""add_is_persistent_to_refresh_tokens

Revision ID: add_is_persistent_to_refresh_tokens
Revises: fix_refresh_tokens_auto_increment
Create Date: 2026-03-12 19:47:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_persistent_to_refresh_tokens'
down_revision = 'fix_refresh_tokens_auto_increment'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens',
                  sa.Column('is_persistent', sa.Boolean(),
                            nullable=True,
                            server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_persistent')
    # ### end Alembic commands ###