"""Add missing tables for hackathon dashboard

Revision ID: add_missing_tables
Revises: add_authentication_tables
Create Date: 2026-02-18 15:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_missing_tables'
down_revision = 'add_authentication_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create projects table
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('repository_url', sa.String(), nullable=True),
        sa.Column('live_url', sa.String(), nullable=True),
        sa.Column('technologies', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=True
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('image_path', sa.String(), nullable=True),
        sa.Column('upvote_count', sa.Integer(), nullable=True),
        sa.Column('downvote_count', sa.Integer(), nullable=True),
        sa.Column('vote_score', sa.Integer(), nullable=True),
        sa.Column('comment_count', sa.Integer(), nullable=True),
        sa.Column('view_count', sa.Integer(), nullable=True),
        sa.Column('hackathon_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id']),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_projects_id'), 'projects', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_projects_title'), 'projects', ['title'], unique=False
    )
    
    # Create hackathons table
    op.create_table(
        'hackathons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('website', sa.String(), nullable=True),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('banner_path', sa.String(), nullable=True),
        sa.Column('participant_count', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=True
        ),
        sa.Column('max_participants', sa.Integer(), nullable=True),
        sa.Column('registration_open', sa.Boolean(), nullable=True),
        sa.Column('prizes', sa.Text(), nullable=True),
        sa.Column('rules', sa.Text(), nullable=True),
        sa.Column('organizers', sa.Text(), nullable=True),
        sa.Column('prize_pool', sa.String(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_hackathons_id'), 'hackathons', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_hackathons_name'), 'hackathons', ['name'], unique=False
    )
    
    # Create hackathon_registrations table
    op.create_table(
        'hackathon_registrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('hackathon_id', sa.Integer(), nullable=True),
        sa.Column(
            'registered_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=True
        ),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', 'hackathon_id', name='_user_hackathon_uc'
        )
    )
    op.create_index(
        op.f('ix_hackathon_registrations_id'),
        'hackathon_registrations', ['id'], unique=False
    )
    
    # Create votes table
    op.create_table(
        'votes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('vote_type', sa.String(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', 'project_id', name='_user_project_vote_uc'
        )
    )
    op.create_index(
        op.f('ix_votes_id'), 'votes', ['id'], unique=False
    )
    
    # Create comments table
    op.create_table(
        'comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('parent_comment_id', sa.Integer(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=True
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('upvote_count', sa.Integer(), nullable=True),
        sa.Column('downvote_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id']),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_comments_id'), 'comments', ['id'], unique=False
    )
    
    # Fix email_verification_tokens table (add used column, remove used_at)
    op.add_column(
        'email_verification_tokens',
        sa.Column(
            'used', sa.Boolean(),
            server_default=sa.text('false'), nullable=True
        )
    )
    op.drop_column('email_verification_tokens', 'used_at')
    
    # Fix password_reset_tokens table (add used column, remove used_at)
    op.add_column(
        'password_reset_tokens',
        sa.Column(
            'used', sa.Boolean(),
            server_default=sa.text('false'), nullable=True
        )
    )
    op.drop_column('password_reset_tokens', 'used_at')
    
    # Add index to users.username
    op.create_index(
        'ix_users_username', 'users', ['username'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_users_username', table_name='users')
    
    # Restore used_at columns
    op.add_column(
        'password_reset_tokens',
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column('password_reset_tokens', 'used')
    
    op.add_column(
        'email_verification_tokens',
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column('email_verification_tokens', 'used')
    
    # Drop tables in reverse order
    op.drop_table('comments')
    op.drop_table('votes')
    op.drop_table('hackathon_registrations')
    op.drop_table('hackathons')
    op.drop_table('projects')
    # ### end Alembic commands ###