"""Add missing tables for hackathon dashboard

Revision ID: add_missing_tables
Revises: add_authentication_tables
Create Date: 2026-02-18 15:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_missing_tables'
down_revision = 'add_authentication_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Since the previous version of this migration failed because
    # tables already exist, we'll take a different approach:
    # 1. Fix authentication tables that might be missing columns
    # 2. Add any missing indexes
    
    # First, ensure refresh_tokens has token_id column
    # We'll use raw SQL to check and add if needed
    conn = op.get_bind()
    
    # Check if refresh_tokens table exists and has token_id
    result = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_name = 'refresh_tokens')"
        )
    ).scalar()
    
    if result:
        # Table exists, check for token_id column
        col_result = conn.execute(
            sa.text(
                "SELECT EXISTS (SELECT FROM information_schema.columns "
                "WHERE table_name = 'refresh_tokens' "
                "AND column_name = 'token_id')"
            )
        ).scalar()
        if not col_result:
            # Add token_id column
            op.add_column(
                'refresh_tokens',
                sa.Column('token_id', sa.String(64), nullable=True)
            )
            # Set temporary values for existing rows
            conn.execute(
                sa.text(
                    "UPDATE refresh_tokens SET token_id = 'temp_' || id "
                    "WHERE token_id IS NULL"
                )
            )
            # Make column NOT NULL
            op.alter_column(
                'refresh_tokens', 'token_id',
                existing_type=sa.String(64),
                nullable=False
            )
            # Create unique index
            op.create_index(
                'ix_refresh_tokens_token_id',
                'refresh_tokens', ['token_id'], unique=True
            )
    
    # Fix email_verification_tokens table
    # Add used column if it doesn't exist
    # Check if column exists first
    col_exists = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT FROM information_schema.columns "
            "WHERE table_name = 'email_verification_tokens' "
            "AND column_name = 'used')"
        )
    ).scalar()
    
    if not col_exists:
        op.add_column(
            'email_verification_tokens',
            sa.Column(
                'used', sa.Boolean(),
                server_default=sa.text('false'), nullable=True
            )
        )
    # Try to drop used_at if it exists (will fail silently if not)
    
    # Fix password_reset_tokens table  
    # Add used column if it doesn't exist
    # Check if column exists first
    col_exists = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT FROM information_schema.columns "
            "WHERE table_name = 'password_reset_tokens' "
            "AND column_name = 'used')"
        )
    ).scalar()
    
    if not col_exists:
        op.add_column(
            'password_reset_tokens',
            sa.Column(
                'used', sa.Boolean(),
                server_default=sa.text('false'), nullable=True
            )
        )
    # Try to drop used_at if it exists (will fail silently if not)
    
    # Add index to users.username (if it doesn't already exist)
    index_exists = conn.execute(
        sa.text(
            "SELECT EXISTS (SELECT FROM pg_indexes "
            "WHERE tablename = 'users' AND indexname = 'ix_users_username')"
        )
    ).scalar()
    
    if not index_exists:
        op.create_index(
            'ix_users_username', 'users', ['username'], unique=True
        )
    
    # Note: We're NOT creating projects, hackathons, etc. tables
    # because they appear to already exist in the database
    # (based on the "relation already exists" error)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_users_username', table_name='users')
    
    # Note: We don't drop columns that were added because
    # they might be needed by the application
    # ### end Alembic commands ###