"""Fix notification schema to match Python models

Revision ID: fix_notification_schema
Revises: add_notification_tables
Create Date: 2026-02-22 08:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fix_notification_schema'
down_revision = 'add_notification_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update notification_types table
    # Rename 'name' column to 'type_key'
    op.alter_column('notification_types', 'name', new_column_name='type_key')
    
    # Add new columns
    op.add_column('notification_types', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notification_types', sa.Column('default_channels', sa.String(length=100), server_default='email,in_app', nullable=True))
    
    # Drop old columns
    op.drop_column('notification_types', 'default_email')
    op.drop_column('notification_types', 'default_push')
    op.drop_column('notification_types', 'default_in_app')
    
    # Update existing data with default values
    op.execute("""
        UPDATE notification_types 
        SET category = 'system',
            default_channels = 'email,in_app'
        WHERE category IS NULL
    """)
    
    # Make new columns NOT NULL after populating
    op.alter_column('notification_types', 'category', nullable=False)
    op.alter_column('notification_types', 'default_channels', nullable=False)
    
    # 2. Recreate user_notification_preferences table with new schema
    # First, drop the old table
    op.drop_table('user_notification_preferences')
    
    # Create new table with correct schema
    op.create_table('user_notification_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('notification_type', sa.String(length=50), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'notification_type', 'channel', name='_user_notification_channel_uc')
    )
    
    # Create index
    op.create_index('ix_user_notification_preferences_user_id', 'user_notification_preferences', ['user_id'])
    
    # 3. Update user_notifications table if needed
    # Check if data column needs to be changed from JSONB to Text
    # (SQLite doesn't support JSONB, so we'll leave it as is for compatibility)
    
    # 4. Update push_subscriptions table if needed
    # Check if user_agent column exists, add if not
    try:
        op.add_column('push_subscriptions', sa.Column('user_agent', sa.Text(), nullable=True))
    except:
        # Column might already exist
        pass
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Revert notification_types table
    op.alter_column('notification_types', 'type_key', new_column_name='name')
    
    # Add back old columns
    op.add_column('notification_types', sa.Column('default_email', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('notification_types', sa.Column('default_push', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('notification_types', sa.Column('default_in_app', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    
    # Drop new columns
    op.drop_column('notification_types', 'category')
    op.drop_column('notification_types', 'default_channels')
    
    # 2. Revert user_notification_preferences table
    op.drop_table('user_notification_preferences')
    
    # Recreate old table
    op.create_table('user_notification_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('notification_type_id', sa.Integer(), nullable=False),
        sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('in_app_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'notification_type_id', name='uq_user_notification_type')
    )
    
    # Create index
    op.create_index('ix_user_notification_preferences_user_id', 'user_notification_preferences', ['user_id'])
    
    # 3. Remove user_agent from push_subscriptions if added
    try:
        op.drop_column('push_subscriptions', 'user_agent')
    except:
        # Column might not exist
        pass
    
    # ### end Alembic commands ###