"""Fix notification schema to match Python models

Revision ID: fix_notification_schema
Revises: add_notification_tables
Create Date: 2026-02-22 08:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fix_notification_schema'
down_revision = 'add_notification_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    def _has_table(table_name: str) -> bool:
        return table_name in inspector.get_table_names()

    def _get_columns(table_name: str) -> set[str]:
        if not _has_table(table_name):
            return set()
        return {col["name"] for col in inspector.get_columns(table_name)}

    def _has_index(table_name: str, index_name: str) -> bool:
        if not _has_table(table_name):
            return False
        return any(
            index["name"] == index_name
            for index in inspector.get_indexes(table_name)
        )
    
    # 1. Update notification_types table
    # Rename 'name' column to 'type_key'
    notification_columns = _get_columns("notification_types")
    if "name" in notification_columns and "type_key" not in notification_columns:
        op.alter_column(
            "notification_types",
            "name",
            new_column_name="type_key"
        )
        notification_columns.remove("name")
        notification_columns.add("type_key")
    
    # Add new columns
    if "category" not in notification_columns:
        op.add_column(
            "notification_types",
            sa.Column("category", sa.String(length=50), nullable=True)
        )
        notification_columns.add("category")
    if "default_channels" not in notification_columns:
        op.add_column(
            "notification_types",
            sa.Column(
                "default_channels",
                sa.String(length=100),
                server_default="email,in_app",
                nullable=True
            )
        )
        notification_columns.add("default_channels")
    
    # Drop old columns
    for column_name in ["default_email", "default_push", "default_in_app"]:
        if column_name in notification_columns:
            op.drop_column("notification_types", column_name)
            notification_columns.remove(column_name)
    
    # Update existing data with default values
    if "category" in notification_columns:
        op.execute("""
            UPDATE notification_types
            SET category = 'system',
                default_channels = 'email,in_app'
            WHERE category IS NULL
        """)
    
    # Make new columns NOT NULL after populating
    if "category" in notification_columns:
        op.alter_column("notification_types", "category", nullable=False)
    if "default_channels" in notification_columns:
        op.alter_column(
            "notification_types",
            "default_channels",
            nullable=False
        )
    
    # 2. Recreate user_notification_preferences table with new schema
    # First, drop the old table
    recreate_preferences = True
    if _has_table("user_notification_preferences"):
        op.drop_table("user_notification_preferences")
    
    
    # Create new table with correct schema
    if recreate_preferences:
        op.create_table('user_notification_preferences',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('notification_type', sa.String(length=50), nullable=False),
            sa.Column('channel', sa.String(length=20), nullable=False),
            sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id', 'notification_type', 'channel', name='_user_notification_channel_uc')
        )
    
    # Create index
    if not _has_index(
        "user_notification_preferences",
        "ix_user_notification_preferences_user_id"
    ):
        op.create_index(
            'ix_user_notification_preferences_user_id',
            'user_notification_preferences',
            ['user_id']
        )
    
    # 3. Update user_notifications table if needed
    # Check if data column needs to be changed from JSONB to Text
    # (SQLite doesn't support JSONB, so we'll leave it as is for compatibility)
    
    # 4. Update push_subscriptions table if needed
    # Check if user_agent column exists, add if not
    push_columns = _get_columns("push_subscriptions")
    if "user_agent" not in push_columns:
        op.add_column(
            'push_subscriptions',
            sa.Column('user_agent', sa.Text(), nullable=True)
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Revert notification_types table
    op.alter_column('notification_types', 'type_key', new_column_name='name')
    
    # Add back old columns
    op.add_column('notification_types', sa.Column('default_email', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('notification_types', sa.Column('default_push', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('notification_types', sa.Column('default_in_app', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    
    # Drop new columns
    op.drop_column('notification_types', 'category')
    op.drop_column('notification_types', 'default_channels')
    
    # 2. Revert user_notification_preferences table
    op.drop_table('user_notification_preferences')
    
    # Recreate old table
    op.create_table('user_notification_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('notification_type_id', sa.Integer(), nullable=False),
        sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('in_app_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'notification_type_id', name='uq_user_notification_type')
    )
    
    # Create index
    op.create_index('ix_user_notification_preferences_user_id', 'user_notification_preferences', ['user_id'])
    
    # 3. Remove user_agent from push_subscriptions if added
    try:
        op.drop_column('push_subscriptions', 'user_agent')
    except:
        # Column might not exist
        pass
    
    # ### end Alembic commands ###